#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           20

bspc config borderless_monocle   true
bspc config focus_follows_pointer true


